DROP TABLE USERS;
CREATE TABLE USERS (
USER_ID INTEGER NOT NULL AUTO_INCREMENT,
USER_NAME VARCHAR(20) NOT NULL UNIQUE,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL,
PRIMARY KEY (USER_ID));
INSERT INTO USERS(USER_NAME, FIRST_NAME, LAST_NAME) VALUES('annfisher', 'Ann', 'Fisher');
INSERT INTO USERS(USER_NAME, FIRST_NAME, LAST_NAME) VALUES('bobking', 'Bob', 'King');
INSERT INTO USERS(USER_NAME, FIRST_NAME, LAST_NAME) VALUES('johnwoo', 'John', 'Woo');
